import { expect, test, type Page } from '@playwright/test'
import { createNewGame } from '../../src/domain/game'

async function clickAction(page: Page, name: string | RegExp) {
  await page.getByRole('button', { name }).click()
}

test('gibt Hinweise stufenweise und zeigt nur den ausdrücklich erfragten Ort auf der Karte', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Mira')
  await clickAction(page, 'Abenteuer starten')
  await page.getByRole('link', { name: 'Aufgaben', exact: true }).click()
  const windQuest = page.locator('.quest-item').filter({ has: page.getByRole('heading', { name: 'Bringe die Windorgel zum Klingen' }) })
  await windQuest.getByText('Kunos Hinweis öffnen', { exact: true }).click()
  await expect(windQuest).toContainText('Hinweis 1:')
  await expect(windQuest).not.toContainText('Das sichtbare Echo')
  await windQuest.getByRole('button', { name: 'Genauerer Hinweis' }).click()
  await expect(windQuest.getByRole('link')).toHaveCount(0)
  await windQuest.getByRole('button', { name: 'Lösung und Ort zeigen' }).click()
  await expect(windQuest).toContainText('Das sichtbare Echo')
  await windQuest.getByRole('link', { name: 'Hinweis auf der Karte ansehen' }).click()
  await expect(page.locator('.map-hint')).toContainText('Kristallmine')
  await expect(page.locator('.map-text-list')).toContainText('Bekannt durch Kunos Hinweis')
  await expect(page.locator('.map-text-list')).not.toContainText('Lorenwerk')
  await page.locator('.map-viewport').scrollIntoViewIfNeeded()
  await expect(page.locator('.map-node').filter({ hasText: 'Kristallmine' })).toBeInViewport()
  await page.reload()
  await expect(page.locator('.map-hint')).toContainText('Kristallmine')
  await page.getByRole('link', { name: 'Aufgaben', exact: true }).click()
  await expect(windQuest.getByText('Kunos Hinweis öffnen (3 von 3)', { exact: true })).toBeVisible()
})

test('kann dieselbe Importdatei nach Abbrechen erneut auswählen und bestätigen', async ({ page }) => {
  await page.goto('/einstellungen')
  const file = { name: 'abenteuer.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(createNewGame('Importkind'))) }
  const input = page.getByLabel('Spielstand importieren', { exact: true })
  await input.setInputFiles(file)
  await expect(page.getByRole('alertdialog')).toContainText('Importkind')
  await page.getByRole('button', { name: 'Abbrechen', exact: true }).click()
  await expect(input).toHaveValue('')
  await input.setInputFiles(file)
  await page.getByRole('button', { name: 'Import bestätigen' }).click()
  await expect(page.getByRole('heading', { name: 'Sonnenwacht', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Sonnenwacht', exact: true })).toBeVisible()
})

test('startet, erkundet, lädt neu und zeigt dieselben Kartendaten', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Mira')
  await page.getByRole('button', { name: 'Abenteuer starten' }).click()

  await expect(page.getByRole('heading', { name: 'Sonnenwacht' })).toBeVisible()
  await page.getByRole('button', { name: /Gehe zum Alten Markt/ }).click()
  await expect(page.getByRole('heading', { name: 'Alter Markt' })).toBeFocused()
  await expect(page.getByRole('heading', { name: 'Alter Markt' })).toBeInViewport()
  await page.getByRole('button', { name: /Nimm die Hebelstange/ }).click()
  await expect(page.locator('.event-result')).toBeFocused()
  await expect(page.locator('.event-result')).toBeInViewport()
  await expect(page.getByRole('listitem').filter({ hasText: 'Hebelstange' })).toBeVisible()

  await page.reload()
  await expect(page.getByRole('heading', { name: 'Alter Markt' })).toBeVisible()
  await expect(page.getByRole('listitem').filter({ hasText: 'Hebelstange' })).toBeVisible()

  await page.getByRole('link', { name: 'Karte' }).click()
  await expect(page.getByRole('heading', { name: 'Entdeckte Orte und Wege' })).toBeVisible()
  await expect(page.getByText('Alter Markt', { exact: true }).last()).toBeVisible()
})

test('enthält keine Vorlesefunktion mehr', async ({ page }) => {
  await page.goto('/einstellungen')
  await expect(page.getByRole('heading', { name: 'Einstellungen' })).toBeVisible()
  await expect(page.getByText(/vorlesen/i)).toHaveCount(0)
})

test('hält bei 320 Pixeln und sehr grosser Schrift Ort und Bedienelemente erreichbar', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('/einstellungen')
  await page.getByText('Sehr gross', { exact: true }).click()
  await expect(page.getByRole('switch', { name: /^Ton/ })).toHaveCount(0)
  await page.getByRole('link', { name: 'TextDungeon – Startseite' }).click()
  await page.getByLabel('Wie heisst du?').fill('Mira')
  await clickAction(page, 'Abenteuer starten')
  const title = page.getByRole('heading', { name: 'Sonnenwacht', exact: true })
  await expect(title).toBeInViewport()
  // Measure in one layout snapshot: the offline-ready notice may appear between
  // two separate browser calls and move both elements down together.
  const titleGap = await page.evaluate(() => {
    const titleBox = document.querySelector('.location-title')!.getBoundingClientRect()
    const toolsBox = document.querySelector('.location-tools')!.getBoundingClientRect()
    return toolsBox.top - titleBox.bottom
  })
  expect(titleGap).toBeLessThan(40)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  await clickAction(page, /Gehe zum Alten Markt/)
  await expect(page.getByRole('heading', { name: 'Alter Markt', exact: true })).toBeInViewport()
  await clickAction(page, 'Inventar')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Inventar', exact: true })).toBeFocused()
})

test('findet den Hafenspeer, zeigt seine Werte und rüstet ihn aus', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Nia')
  await page.getByRole('button', { name: 'Abenteuer starten' }).click()

  await page.getByRole('button', { name: /Gehe zum Alten Markt/ }).click()
  await page.getByRole('button', { name: /Nimm die Hebelstange/ }).click()
  await page.getByRole('button', { name: /Gehe nach Sonnenwacht/ }).click()
  await page.getByRole('button', { name: /Gehe zum Drei-Wege-Platz/ }).click()
  await page.getByRole('button', { name: /Folge dem Weg zur Küste/ }).click()
  await page.getByRole('button', { name: /Gehe zum Muschelhafen/ }).click()
  await page.getByRole('button', { name: /Gehe zum überfluteten Markt/ }).click()
  await page.getByRole('button', { name: /Heble den Marktstand hoch/ }).click()
  await page.getByRole('button', { name: /Kehre zum Muschelhafen zurück/ }).click()
  await page.getByRole('button', { name: /Öffne Nelas Hafentruhe/ }).click()

  await page.getByRole('button', { name: 'Inventar' }).click()
  await page.getByRole('button', { name: /Hafenspeer/ }).click()
  await expect(page.getByRole('heading', { name: 'Hafenspeer' })).toBeVisible()
  await expect(page.getByText('3–5')).toBeVisible()
  await expect(page.getByText('Bonus gegen Wassergegner')).toBeVisible()
  await page.getByRole('button', { name: 'Ausrüsten' }).click()
  await expect(page.getByRole('button', { name: 'Ausgerüstet' })).toBeVisible()
  await page.getByRole('button', { name: 'Inventar schliessen' }).click()

  await expect(page.locator('.quick-status')).toContainText('Hafenspeer')
  await page.reload()
  await expect(page.locator('.quick-status')).toContainText('Hafenspeer')
})

test('speichert einen laufenden Kampf und setzt ihn bei Flucht zurück', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Pia')
  await page.getByRole('button', { name: 'Abenteuer starten' }).click()
  await clickAction(page, /Gehe zum Drei-Wege-Platz/)
  await clickAction(page, /Folge dem Weg zur Küste/)
  await clickAction(page, /Gehe zum Muschelhafen/)
  await clickAction(page, /Gehe zum überfluteten Markt/)
  await clickAction(page, /Stelle dich dem Pfützenhopser/)

  await expect(page.getByRole('heading', { name: 'Pfützenhopser' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Spritzender Hüpfer' })).toBeVisible()
  await clickAction(page, /Angreifen/)
  await expect(page.getByRole('heading', { name: 'Weiter Sprung' })).toBeVisible()
  await expect(page.getByRole('progressbar', { name: /Pfützenhopser: [4-6] von 8 Leben/ })).toBeVisible()

  await expect(page.locator('.save-state')).toHaveText('Gespeichert')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Weiter Sprung' })).toBeVisible()
  await clickAction(page, /^Fliehen/)
  await expect(page.getByRole('heading', { name: 'Muschelhafen' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pfützenhopser' })).toHaveCount(0)
})

test('spielt den vollständigen Quelltränenweg und öffnet den Aquädukt', async ({ page }) => {
  test.setTimeout(75_000)
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Ari')
  await page.getByRole('button', { name: 'Abenteuer starten' }).click()

  await clickAction(page, /Gehe zum Alten Markt/)
  await clickAction(page, /Nimm die Hebelstange/)
  await clickAction(page, /Gehe zum Garten der Namen/)
  await clickAction(page, /^Untersuche den Ort /)
  for (const name of ['Wind', 'Licht', 'Wasser', 'Wachstum']) await page.getByRole('button', { name, exact: true }).click()
  await clickAction(page, /Ordne die Symbolsteine/)
  await clickAction(page, /Gehe zum Alten Markt/)
  await clickAction(page, /Gehe nach Sonnenwacht/)
  await clickAction(page, /Gehe zum Drei-Wege-Platz/)
  await clickAction(page, /Folge dem Weg zur Küste/)
  await clickAction(page, /Gehe zum Muschelhafen/)
  await clickAction(page, /Gehe zum überfluteten Markt/)
  await clickAction(page, /Heble den Marktstand hoch/)
  await clickAction(page, /Kehre zum Muschelhafen zurück/)
  await clickAction(page, /Steige den Küstenpfad hinauf/)
  await clickAction(page, /Steige zum Drei-Wege-Platz hinauf/)
  await clickAction(page, /Gehe zur Eichenpforte/)
  await clickAction(page, /Gehe zum Funkelpfad/)
  await clickAction(page, /Gehe zum Försterhaus/)
  await clickAction(page, /Gehe zum Glühgarten/)
  await clickAction(page, /Gehe zur Alten Baumschule/)
  await clickAction(page, /^Untersuche den Ort /)
  await clickAction(page, /Nimm etwas Mondmoos/)
  await clickAction(page, /Gehe zum Glühgarten/)
  await clickAction(page, /Gehe zur Mooslichtung/)
  await clickAction(page, /Gehe zur Eichenpforte/)
  await clickAction(page, /Gehe zum Drei-Wege-Platz/)
  await clickAction(page, /Folge dem Weg zur Küste/)
  await clickAction(page, /Gehe zum Muschelhafen/)
  await clickAction(page, /Gehe zum überfluteten Markt/)
  await clickAction(page, /Gehe zum Schleusenhaus/)
  await clickAction(page, /^Untersuche den Ort /)
  await page.getByLabel('Ablauf', { exact: true }).selectOption('0')
  await page.getByLabel('Quelltor', { exact: true }).selectOption('1')
  await clickAction(page, /Repariere und stelle die Schleuse/)
  await clickAction(page, /Gehe zur Korallengrotte/)
  await clickAction(page, /Empfange die Quellträne/)

  await expect(page.getByText(/Quellträne/).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /Alter Aquädukt/ })).toBeVisible()
})

test('speichert Rätselteile, verwirft falsche Folgen und spielt nach Offline-Neuladen weiter', async ({ page, context }) => {
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Lio')
  await clickAction(page, 'Abenteuer starten')
  await clickAction(page, /Gehe zum Alten Markt/)
  await clickAction(page, /Gehe zum Garten der Namen/)
  await clickAction(page, /^Untersuche den Ort /)
  await expect(page.getByRole('button', { name: /Ordne die Symbolsteine/ })).toHaveAttribute('aria-disabled', 'true')
  await page.getByRole('button', { name: 'Wasser', exact: true }).click()
  await expect(page.locator('.event-result')).toContainText('beginnt von vorn')
  await page.getByRole('button', { name: 'Wind', exact: true }).click()
  await expect(page.locator('.puzzle-panel')).toContainText('Folge: 1 von 4')
  await expect(page.locator('.save-state')).toHaveText('Gespeichert')
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise<void>((resolve) => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), { once: true }))
  })
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Garten der Namen' })).toBeVisible()
  await expect(page.locator('.puzzle-panel')).toContainText('Folge: 1 von 4')
  for (const name of ['Licht', 'Wasser', 'Wachstum']) await page.getByRole('button', { name, exact: true }).click()
  await clickAction(page, /Ordne die Symbolsteine/)
  await expect(page.locator('.carried-items')).toContainText('Archivschlüssel')
  await clickAction(page, 'Inventar')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('#root')).toHaveJSProperty('inert', true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Inventar', exact: true })).toBeFocused()
  await expect(page.locator('#root')).toHaveJSProperty('inert', false)
})

test('weist einen unbekannten Import-Ort zurück und behält das laufende Abenteuer', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Wie heisst du?').fill('Mira')
  await clickAction(page, 'Abenteuer starten')
  await clickAction(page, /Gehe zum Alten Markt/)
  await expect(page.locator('.save-state')).toHaveText('Gespeichert')
  const save = await page.evaluate(async () => {
    const database = await new Promise<IDBDatabase>((resolve) => { const request = indexedDB.open('textdungeon'); request.onsuccess = () => resolve(request.result) })
    const stored = await new Promise<{ value: Record<string, unknown> }>((resolve) => { const request = database.transaction('adventures').objectStore('adventures').get('current'); request.onsuccess = () => resolve(request.result) })
    database.close()
    return stored.value
  })
  await page.getByRole('link', { name: 'Einstellungen' }).click()
  await page.getByLabel('Spielstand importieren', { exact: true }).setInputFiles({ name: 'kaputt.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...save, currentAreaId: 'nirgendwo', visitedAreaIds: ['sonnenwacht', 'nirgendwo'] })) })
  await expect(page.getByRole('alert')).toContainText('unbekannter Eintrag')
  await expect(page.getByRole('button', { name: 'Import bestätigen' })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.save-summary')).toContainText('Alter Markt')
  await expect(page.locator('.save-summary')).toContainText('Mira')
})
